### ISSUE TITLE
Break dependency upon WinGraphviz

### ISSUE THREAD

**Issue by GoogleCodeExporter** [drewnoakes/dependency-analyser#2]
WinGraphviz is great, but it increases the barrier to entry for this tool.

See [this question on StackOverflow](http://stackoverflow.com/q/589900/24874) that details various options.

_Original issue reported on code.google.com by `drewnoakes` on 22 Apr 2011 at 8:55_

**Comment by jeremysimmons** [comment]
Maybe the barrier for entry is the lack of an installer?
If the GraphViz COM DLL could be embedded and automatically unpacked/used, that could solve the issue...
Registration-Free COM Interop - https://msdn.microsoft.com/en-us/library/fh1h056h(v=vs.110).aspx

**Comment by jeremysimmons** [comment]
Another possibility would be bootstrapping the GraphVIZ DLL. 
1. upload the DLL to the git repository
2. add code to download the DLL via cdn.rawgit.com to the machine if it's missing

On second though. This is a bad idea. The DLL is 340 zipped. Adding as an assembly resource and uncompressing/loading should be more than sufficient.

**Comment by drewnoakes** [comment]
Avoiding separate installation of GraphViz would be great. Can it just be
included in the release zip, and picked up from the local directory somehow
at runtime, without needing any registry tweaks or other
admin-rights-requiring activities.

**Comment by jeremysimmons** [comment]
Picking up the com registrations is what registry free com is all about. Good set of resources on building the manifest definitions
http://stackoverflow.com/questions/465882/generate-manifest-files-for-registration-free-com

**Comment by drewnoakes** [comment]
Another option is to migrate to WPF and use [Graph#](http://graphsharp.codeplex.com/).

**Comment by jeremysimmons** [comment]
an option worth considering for sure!

any downsides?

**Comment by drewnoakes** [comment]
Another option: https://github.com/microsoft/automatic-graph-layout

**Comment by drewnoakes** [comment]
This has been completed.
