### ISSUE TITLE
Support .sln files for newer versions of visual studio

### ISSUE THREAD

**Issue by GoogleCodeExporter** [drewnoakes/dependency-analyser#4]
```
Pretty self explanatory.
```

Original issue reported on code.google.com by `drewnoakes` on 22 Apr 2011 at 9:11

**Comment by jeremysimmons** [comment]
merge with #9

**Comment by drewnoakes** [comment]
@jeremysimmons are these the same? This issue is about support for parsing newer versions of the `.sln` file format, and #9 is about being able to read metadata from assemblies compiled for newer versions of the .NET runtime. They definitely related, but could be tracked and completed separately.

**Comment by drewnoakes** [comment]
Fixed.
