### ISSUE TITLE
Support project files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [drewnoakes/dependency-analyser#5]
```
Allow user to create a project file that stores the location(s) of assembl(ies) 
to be analysed, and any filtering that should be applied to the results.

(As an aside, this project file might be useful for a command-line version of 
the tool.)
```

Original issue reported on code.google.com by `drewnoakes` on 22 Apr 2011 at 9:14

**Comment by jeremysimmons** [comment]
merge this with #6 ?

**Comment by drewnoakes** [comment]
@jeremysimmons I think #6 is more about being able to load a second solution and not have it blow the nodes from the first solution away. IIRC currently that's what happens, rather than merging graphs. If I'm wrong, then #5 could be closed.
