### ISSUE TITLE
Support analysis of multiple .sln files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [drewnoakes/dependency-analyser#6]
```
Currently we only support merging analysis results of assemblies (.dll and .exe 
files.)

It may be useful to some people to allow merging analysis results from multiple 
.sln files.
```

Original issue reported on code.google.com by `drewnoakes` on 22 Apr 2011 at 9:16

**Comment by jeremysimmons** [comment]
This looks like a reasonable way to get access to the Solution and Project files.
https://www.nuget.org/packages/Onion.SolutionParser.Parser

I wouldn't want to build the solution to obtain the outputs, but perhaps the output filename could be derived.

**Comment by drewnoakes** [comment]
Nice find. I can't tell from their [readme](https://github.com/ost-onion/SolutionParser) whether project references are available, but I suspect even if they're not then it'd be a nice PR for their project.

Looking at the [source](https://github.com/ost-onion/SolutionParser/blob/master/src/Onion.SolutionParser.Parser/Model/ProjectSection.cs), perhaps references are available in a so-called `ProjectSection` which has an `IDictionary<string,string>`

**Comment by drewnoakes** [comment]
Fixed.
